const muhurtaValues = [
  /* duration from sunrise to next sunrise / 30. same order every day */
  { num: 1, name: "muhurta__1", quality: "guna__m", exDays: [] },
  { num: 2, name: "muhurta__2", quality: "guna__m", exDays: [] },
  { num: 3, name: "muhurta__3", quality: "guna__b", exDays: [] },
  { num: 4, name: "muhurta__4", quality: "guna__m", exDays: [] },
  { num: 5, name: "muhurta__5", quality: "guna__b", exDays: [] },
  { num: 6, name: "muhurta__6", quality: "guna__b", exDays: [] },
  { num: 7, name: "muhurta__7", quality: "guna__b", exDays: [] },
  { num: 8, name: "muhurta__8", quality: "guna__b", exDays: [1, 5] },
  { num: 9, name: "muhurta__9", quality: "guna__b", exDays: [] },
  { num: 10, name: "muhurta__10", quality: "guna__m", exDays: [] },
  { num: 11, name: "muhurta__11", quality: "guna__m", exDays: [] },
  { num: 12, name: "muhurta__12", quality: "guna__m", exDays: [] },
  { num: 13, name: "muhurta__13", quality: "guna__b", exDays: [] },
  { num: 14, name: "muhurta__14", quality: "guna__b", exDays: [0] },
  { num: 15, name: "muhurta__15", quality: "guna__m", exDays: [] },
  { num: 16, name: "muhurta__16", quality: "guna__m", exDays: [] },
  { num: 17, name: "muhurta__17", quality: "guna__m", exDays: [] },
  { num: 18, name: "muhurta__18", quality: "guna__b", exDays: [] },
  { num: 19, name: "muhurta__19", quality: "guna__b", exDays: [] },
  { num: 20, name: "muhurta__20", quality: "guna__b", exDays: [] },
  { num: 21, name: "muhurta__21", quality: "guna__m", exDays: [] },
  { num: 22, name: "muhurta__22", quality: "guna__b", exDays: [] },
  { num: 23, name: "muhurta__23", quality: "guna__b", exDays: [] },
  { num: 24, name: "muhurta__24", quality: "guna__b", exDays: [] },
  { num: 25, name: "muhurta__25", quality: "guna__b", exDays: [] },
  { num: 26, name: "muhurta__26", quality: "guna__b", exDays: [] },
  { num: 27, name: "muhurta__27", quality: "guna__b", exDays: [] },
  { num: 28, name: "muhurta__28", quality: "guna__b", exDays: [] },
  { num: 29, name: "muhurta__27", quality: "guna__b", exDays: [] },
  { num: 30, name: "muhurta__28", quality: "guna__b", exDays: [] },
];

export default muhurtaValues;