const yogaValues = [
    { num: 1, name: "yoga__1", ruler: "sa", bm: "guna__m" },
    { num: 2, name: "yoga__2", ruler: "me", bm: "guna__b" },
    { num: 3, name: "yoga__3", ruler: "ke", bm: "guna__b" },
    { num: 4, name: "yoga__4", ruler: "ve", bm: "guna__b" },
    { num: 5, name: "yoga__5", ruler: "su", bm: "guna__b" },
    { num: 6, name: "yoga__6", ruler: "mo", bm: "guna__m" },
    { num: 7, name: "yoga__7", ruler: "ma", bm: "guna__b" },
    { num: 8, name: "yoga__8", ruler: "ra", bm: "guna__b" },
    { num: 9, name: "yoga__9", ruler: "ju", bm: "guna__m" },
    { num: 10, name: "yoga__10", ruler: "sa", bm: "guna__m" },
    { num: 11, name: "yoga__11", ruler: "me", bm: "guna__b" },
    { num: 12, name: "yoga__12", ruler: "ke", bm: "guna__b" },
    { num: 13, name: "yoga__13", ruler: "ve", bm: "guna__m" },
    { num: 14, name: "yoga__14", ruler: "su", bm: "guna__b" },
    { num: 15, name: "yoga__15", ruler: "mo", bm: "guna__m" },
    { num: 16, name: "yoga__16", ruler: "ma", bm: "guna__b" },
    { num: 17, name: "yoga__17", ruler: "ra", bm: "guna__m" },
    { num: 18, name: "yoga__18", ruler: "ju", bm: "guna__b" },
    { num: 19, name: "yoga__19", ruler: "sa", bm: "guna__m" },
    { num: 20, name: "yoga__20", ruler: "me", bm: "guna__b" },
    { num: 21, name: "yoga__21", ruler: "ke", bm: "guna__b" },
    { num: 22, name: "yoga__22", ruler: "ve", bm: "guna__b" },
    { num: 23, name: "yoga__23", ruler: "su", bm: "guna__b" },
    { num: 24, name: "yoga__24", ruler: "mo", bm: "guna__b" },
    { num: 25, name: "yoga__25", ruler: "ma", bm: "guna__b" },
    { num: 26, name: "yoga__26", ruler: "ra", bm: "guna__b" },
    { num: 27, name: "yoga__27", ruler: "ju", bm: "guna__m" },
];

export default yogaValues;