/*
These are default payment values and will be stored as a setting
*/

const paymentValues = [
  {
    key: 'bronze__trial',
    name: 'Bronze trial',
    period: 'days',
    duration: 3,
    curr: 'USD',
    amount: 0.0,
    maxRepeats: 0,
  },
  {
    key: 'bronze__weekly',
    name: 'Bronze weekly',
    period: 'days',
    duration: 7,
    curr: 'USD',
    amount: 2.0,
    maxRepeats: 51,
  },
  {
    key: 'bronze__monthly',
    name: 'Bronze monthly',
    period: 'month',
    duration: 1,
    curr: 'USD',
    amount: 5.0,
    maxRepeats: 11,
  },
  {
    key: 'bronze__yearly',
    name: 'Bronze yearly',
    period: 'year',
    duration: 1,
    curr: 'USD',
    amount: 50.0,
    maxRepeats: 0,
  },
  {
    key: 'silver__trial',
    name: 'Silver trial',
    period: 'days',
    duration: 3,
    curr: 'USD',
    amount: 0.0,
    maxRepeats: 0,
  },
  {
    key: 'silver__monthly',
    name: 'Silver monthly',
    period: 'month',
    duration: 1,
    curr: 'USD',
    amount: 10.0,
    maxRepeats: 11,
  },
  {
    key: 'silver__yearly',
    name: 'silver yearly',
    period: 'year',
    duration: 1,
    curr: 'USD',
    amount: 100.0,
    maxRepeats: 0,
  },
  {
    key: 'star__trial',
    name: 'Star trial',
    period: 'days',
    duration: 3,
    curr: 'USD',
    amount: 0.0,
    maxRepeats: 0,
  },
  {
    key: 'star__monthly',
    name: 'Star monthly',
    period: 'month',
    duration: 1,
    curr: 'USD',
    amount: 11.0,
    maxRepeats: 11,
  },
  {
    key: 'star__yearly',
    name: 'gold yearly',
    period: 'year',
    duration: 1,
    curr: 'USD',
    amount: 110.0,
    maxRepeats: 0,
  },
  {
    key: 'gold__trial',
    name: 'Gold trial',
    period: 'days',
    duration: 3,
    curr: 'USD',
    amount: 0.0,
    maxRepeats: 0,
  },
  {
    key: 'gold__monthly',
    name: 'Gold monthly',
    period: 'month',
    duration: 1,
    curr: 'USD',
    amount: 15.0,
    maxRepeats: 11,
  },

  {
    key: 'gold__yearly',
    name: 'Gold yearly',
    period: 'year',
    duration: 1,
    curr: 'USD',
    amount: 150.0,
    maxRepeats: 0,
  },
];

export default paymentValues;
