const ayanamshaValues = [
  { key: 'fagan_bradley', value: 0 },
  { key: 'lahiri', value: 1 },
  { key: 'deluce', value: 2 },
  { key: 'raman', value: 3 },
  { key: 'ushashashi', value: 4 },
  { key: 'krishnamurti', value: 5 },
  { key: 'djwhal_khul', value: 6 },
  { key: 'yukteshwar', value: 7 },
  { key: 'jn_bhasin', value: 8 },
  { key: 'babyl_kugler1', value: 9 },
  { key: 'babyl_kugler2', value: 10 },
  { key: 'babyl_kugler3', value: 11 },
  { key: 'babyl_huber', value: 12 },
  { key: 'babyl_etpsc', value: 13 },
  { key: 'aldebaran_15tau', value: 14 },
  { key: 'hipparchos', value: 15 },
  { key: 'sassanian', value: 16 },
  { key: 'galcent_0sag', value: 17 },
  { key: 'j2000', value: 18 },
  { key: 'j1900', value: 19 },
  { key: 'b1950', value: 20 },
  { key: 'suryasiddhanta', value: 21 },
  { key: 'suryasiddhanta_msun', value: 22 },
  { key: 'aryabhata', value: 23 },
  { key: 'aryabhata_msun', value: 24 },
  { key: 'ss_revati', value: 25 },
  { key: 'ss_citra', value: 26 },
  { key: 'true_citra', value: 27 },
  { key: 'true_revati', value: 28 },
  { key: 'true_pushya', value: 29 },
  { key: 'galcent_rgbrand', value: 30 },
  { key: 'galequ_iau1958', value: 31 },
  { key: 'galequ_true', value: 32 },
  { key: 'galequ_mula', value: 33 },
  { key: 'galalign_mardyks', value: 34 },
  { key: 'true_mula', value: 35 },
  { key: 'galcent_mula_wilhelm', value: 36 },
  { key: 'aryabhata_522', value: 37 },
  { key: 'babyl_britton', value: 38 },
  { key: 'true_sheoran', value: 39 },
  { key: 'galcent_cochrane', value: 40 },
  { key: 'galequ_fiorenza', value: 41 },
  { key: 'valens_moon', value: 42 },
  { key: 'user', value: 255 },
];

export default ayanamshaValues;
