const muhurtaValues = [
  /* duration from sunrise to next sunrise / 30. same order every day */
  { num: 1, name: "rudra", quality: "inauspicious", exDays: [] },
  { num: 2, name: "āhi", quality: "inauspicious", exDays: [] },
  { num: 3, name: "mitra ", quality: "auspicious", exDays: [] },
  { num: 4, name: "pitṝ", quality: "inauspicious", exDays: [] },
  { num: 5, name: "vasu", quality: "auspicious", exDays: [] },
  { num: 6, name: "vārāha", quality: "auspicious", exDays: [] },
  { num: 7, name: "viśvedevā", quality: "auspicious", exDays: [] },
  { num: 8, name: "vidhi", quality: "auspicious", exDays: [1, 5] },
  { num: 9, name: "sutamukhī", quality: "auspicious", exDays: [] },
  { num: 10, name: "puruhūta", quality: "inauspicious", exDays: [] },
  { num: 11, name: "vāhinī", quality: "inauspicious", exDays: [] },
  { num: 12, name: "naktanakarā", quality: "inauspicious", exDays: [] },
  { num: 13, name: "varuṇa", quality: "auspicious", exDays: [] },
  { num: 14, name: "aryaman", quality: "auspicious", exDays: [0] },
  { num: 15, name: "bhaga", quality: "inauspicious", exDays: [] },
  { num: 16, name: "girīśa", quality: "inauspicious", exDays: [] },
  { num: 17, name: "ajapāda", quality: "inauspicious", exDays: [] },
  { num: 18, name: "ahir-budhnya", quality: "auspicious", exDays: [] },
  { num: 19, name: "puṣya", quality: "auspicious", exDays: [] },
  { num: 20, name: "aśvinī", quality: "auspicious", exDays: [] },
  { num: 21, name: "yama", quality: "inauspicious", exDays: [] },
  { num: 22, name: "agni", quality: "auspicious", exDays: [] },
  { num: 23, name: "vidhātṛ", quality: "auspicious", exDays: [] },
  { num: 24, name: "kaṇḍa", quality: "auspicious", exDays: [] },
  { num: 25, name: "aditi", quality: "auspicious", exDays: [] },
  { num: 26, name: "jīva/amṛta", quality: "very auspicious", exDays: [] },
  { num: 27, name: "viṣṇu", quality: "auspicious", exDays: [] },
  { num: 28, name: "dyumadgadyuti", quality: "auspicious", exDays: [] },
  { num: 29, name: "brahma", quality: "very auspicious", exDays: [] },
  { num: 30, name: "samudram", quality: "auspicious", exDays: [] },
];

module.exports = muhurtaValues;