const nakshatraValues = [
  { name: "Aśvini", ruler: "ke", goal: "dharma", sex: "m", yoni: "aśva", aksharas: ["a ", "i ", "u ", "e "], nadi: "vt" },
  { name: "Bharaṇī", ruler: "ve", goal: "artha", sex: "f", yoni: "gaja", aksharas: ["o ", "va", "vi", "vu"], nadi: "pt" },
  { name: "Kṛttikā", ruler: "su", goal: "kama", sex: "f", yoni: "meṣa", aksharas: ["ve", "vo", "ka", "ki"], nadi: "kp" },
  { name: "Rohiṇī", ruler: "mo", goal: "moksha", sex: "f", yoni: "sarpa", aksharas: ["ku", "gh", "ṅa", "ch"], nadi: "kp" },
  { name: "Mṛgaśīrṣā", ruler: "ma", goal: "moksha", sex: "None", yoni: "sarpa", aksharas: ["ke", "ko", "ha", "hi"], nadi: "pt" },
  { name: "Ārdrā", ruler: "ra", goal: "kama", sex: "f", yoni: "svan", aksharas: ["hu", "he", "ho", "ḍa"], nadi: "vt" },
  { name: "Punarvasu", ruler: "ju", goal: "artha", sex: "m", yoni: "mārjāraḥ", aksharas: ["ḍi", "ḍu", "ḍe", "ḍo"], nadi: "vt" },
  { name: "Puṣya", ruler: "sa", goal: "dharma", sex: "m", yoni: "meṣa", aksharas: ["ma", "mi", "mu", "me"], nadi: "pt" },
  { name: "Āśleṣā", ruler: "me", goal: "dharma", sex: "f", yoni: "mārjāraḥ", aksharas: ["mo", "ṭa", "ṭi", "ṭu"], nadi: "kp" },
  { name: "Maghā", ruler: "ke", goal: "artha", sex: "f", yoni: "mūṣika", aksharas: ["ṭe", "ṭo", "pa", "pi"], nadi: "kp" },
  { name: "Pūrva Phālgunī", ruler: "ve", goal: "kama", sex: "f", yoni: "mūṣika", aksharas: ["pu", "ṣa", "ṇa", "ṭh"], nadi: "pt" },
  { name: "Uttara Phālgunī", ruler: "su", goal: "moksha", sex: "f", yoni: "go", aksharas: ["pe", "po", "ra", "ri"], nadi: "vt" },
  { name: "Hastā", ruler: "mo", goal: "moksha", sex: "m", yoni: "mahaḥ", aksharas: ["ru", "re", "ro", "ta"], nadi: "vt" },
  { name: "Citrā", ruler: "ma", goal: "kama", sex: "f", yoni: "vyāghra", aksharas: ["ti", "tu", "te", "to"], nadi: "pt" },
  { name: "Svāti", ruler: "ra", goal: "artha", sex: "f", yoni: "mahaḥ", aksharas: ["na", "ni", "nu", "ne"], nadi: "kp" },
  { name: "Viśākhā", ruler: "ju", goal: "dharma", sex: "f", yoni: "vyāghra", aksharas: ["no", "ya", "yi", "yu"], nadi: "kp" },
  { name: "Anurādhā", ruler: "sa", goal: "dharma", sex: "m", yoni: "mṛga", aksharas: ["ye", "yo", "bh", "bh"], nadi: "pt" },
  { name: "Jyeṣṭhā", ruler: "me", goal: "artha", sex: "f", yoni: "mṛga", aksharas: ["bh", "dh", "ph", "ḍh"], nadi: "vt" },
  { name: "Mūla", ruler: "ke", goal: "kama", sex: "None", yoni: "svan", aksharas: ["bh", "bh", "ja", "ji"], nadi: "vt" },
  { name: "Pūrva Aṣāḍhā", ruler: "ve", goal: "moksha", sex: "f", yoni: "vānara", aksharas: ["ju", "je", "jo", "kh"], nadi: "pt" },
  { name: "Uttara Aṣāḍhā", ruler: "su", goal: "moksha", sex: "f", yoni: "nakula", aksharas: ["kh", "kh", "kh", "kh"], nadi: "kp" },
  { name: "Śrāvaṇa", ruler: "mo", goal: "artha", sex: "m", yoni: "vānara", aksharas: ["go", "sa", "si", "su"], nadi: "kp" },
  { name: "Dhaniṣṭhā", ruler: "ma", goal: "dharma", sex: "f", yoni: "siṃha", aksharas: ["se", "so", "da", "di"], nadi: "pt" },
  { name: "Śatabhiṣā", ruler: "ra", goal: "dharma", sex: "None", yoni: "aśva", aksharas: ["du", "th", "jh", "ña"], nadi: "vt" },
  { name: "Pūrva Bhādrapadā", ruler: "ju", goal: "artha", sex: "m", yoni: "siṃha", aksharas: ["de", "do", "ca", "ci"], nadi: "vt" },
  { name: "Uttara Bhādrapadā", ruler: "sa", goal: "artha", sex: "m", yoni: "go", aksharas: ["cu", "ce", "co", "la"], nadi: "pt" },
  { name: "Revati", ruler: "me", goal: "moksha", sex: "f", yoni: "gaja", aksharas: ["li", "lu", "le", "lo"], nadi: "kp" },
];

export default nakshatraValues;