const values = [
    { num: 1, paksha: "śuklapakṣa", tithi: "pratipadā", lord: "su", div: "nanda" },
    { num: 2, paksha: "śuklapakṣa", tithi: "dvitīyā", lord: "mo", div: "bhadra" },
    { num: 3, paksha: "śuklapakṣa", tithi: "tṛtīyā", lord: "ma", div: "Jaya" },
    { num: 4, paksha: "śuklapakṣa", tithi: "caturthī", lord: "me", div: "rikta" },
    { num: 5, paksha: "śuklapakṣa", tithi: "pancamī", lord: "ju", div: "pūrṇa" },
    { num: 6, paksha: "śuklapakṣa", tithi: "ṣaṣthī", lord: "ve", div: "nanda" },
    { num: 7, paksha: "śuklapakṣa", tithi: "saptamī", lord: "sa", div: "bhadra" },
    { num: 8, paksha: "śuklapakṣa", tithi: "aṣṭamī", lord: "ra", div: "jaya" },
    { num: 9, paksha: "śuklapakṣa", tithi: "navamī", lord: "su", div: "rikta" },
    { num: 10, paksha: "śuklapakṣa", tithi: "daśamī", lord: "mo", div: "pūrṇa" },
    { num: 11, paksha: "śuklapakṣa", tithi: "ekādaśī", lord: "ma", div: "nanda" },
    { num: 12, paksha: "śuklapakṣa", tithi: "dvādaśī", lord: "me", div: "bhadra" },
    { num: 13, paksha: "śuklapakṣa", tithi: "trayodaśī", lord: "ju", div: "jaya" },
    { num: 14, paksha: "śuklapakṣa", tithi: "caturdaśī", lord: "ve", div: "rikta" },
    { num: 15, paksha: "śuklapakṣa", tithi: "pūrṇimā", lord: "sa", div: "pūrṇa" },
    { num: 16, paksha: "kṛṣṇapakṣa", tithi: "pratipadā", lord: "su", div: "nanda" },
    { num: 17, paksha: "kṛṣṇapakṣa", tithi: "dvitīyā", lord: "mo", div: "bhadra" },
    { num: 18, paksha: "kṛṣṇapakṣa", tithi: "tṛtīyā", lord: "ma", div: "jaya" },
    { num: 19, paksha: "kṛṣṇapakṣa", tithi: "caturthī", lord: "me", div: "rikta" },
    { num: 20, paksha: "kṛṣṇapakṣa", tithi: "pancamī", lord: "ju", div: "pūrṇa" },
    { num: 21, paksha: "kṛṣṇapakṣa", tithi: "ṣaṣthī", lord: "ve", div: "nanda" },
    { num: 22, paksha: "kṛṣṇapakṣa", tithi: "saptamī", lord: "sa", div: "bhadra" },
    { num: 23, paksha: "kṛṣṇapakṣa", tithi: "aṣṭamī", lord: "ra", div: "jaya" },
    { num: 24, paksha: "kṛṣṇapakṣa", tithi: "navamī", lord: "su", div: "rikta" },
    { num: 25, paksha: "kṛṣṇapakṣa", tithi: "daśamī", lord: "mo", div: "pūrṇa" },
    { num: 26, paksha: "kṛṣṇapakṣa", tithi: "ekādaśī", lord: "ma", div: "nanda" },
    { num: 27, paksha: "kṛṣṇapakṣa", tithi: "dvādaśī", lord: "me", div: "bhadra" },
    { num: 28, paksha: "kṛṣṇapakṣa", tithi: "trayodaśī", lord: "ju", div: "jaya" },
    { num: 29, paksha: "kṛṣṇapakṣa", tithi: "caturdaśī", lord: "ve", div: "rikta" },
    { num: 30, paksha: "kṛṣṇapakṣa", tithi: "amāvasyā", lord: "ra", div: "pūrṇa" },
];

export default values;
