const yogaValues = [
    { num: 1, name: "viṣkambha", ruler: "sa", bm: "m" },
    { num: 2, name: "prīti", ruler: "me", bm: "b" },
    { num: 3, name: "āyuśmān", ruler: "ke", bm: "b" },
    { num: 4, name: "saubhāgya", ruler: "ve", bm: "b" },
    { num: 5, name: "śobhana", ruler: "su", bm: "b" },
    { num: 6, name: "atigaṇḍa", ruler: "mo", bm: "m" },
    { num: 7, name: "sukarma", ruler: "ma", bm: "b" },
    { num: 8, name: "dhṛti", ruler: "ra", bm: "b" },
    { num: 9, name: "śūla", ruler: "ju", bm: "m" },
    { num: 10, name: "gaṇḍa", ruler: "sa", bm: "m" },
    { num: 11, name: "vṛddhi", ruler: "me", bm: "b" },
    { num: 12, name: "dhruva", ruler: "ke", bm: "b" },
    { num: 13, name: "vyāghatā", ruler: "ve", bm: "m" },
    { num: 14, name: "harṣaṇa", ruler: "su", bm: "b" },
    { num: 15, name: "vajra", ruler: "mo", bm: "m" },
    { num: 16, name: "siddhi", ruler: "ma", bm: "b" },
    { num: 17, name: "vyatipāta", ruler: "ra", bm: "m" },
    { num: 18, name: "variyas", ruler: "ju", bm: "b" },
    { num: 19, name: "parigha", ruler: "sa", bm: "m" },
    { num: 20, name: "śiva", ruler: "me", bm: "b" },
    { num: 21, name: "siddha", ruler: "ke", bm: "b" },
    { num: 22, name: "sādhya", ruler: "ve", bm: "b" },
    { num: 23, name: "śubha", ruler: "su", bm: "b" },
    { num: 24, name: "śukla", ruler: "mo", bm: "b" },
    { num: 25, name: "brahma", ruler: "ma", bm: "b" },
    { num: 26, name: "māhendra", ruler: "ra", bm: "b" },
    { num: 27, name: "vaidhṛti", ruler: "ju", bm: "m" },
];

export default yogaValues;